//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order
    {
        public int OrderID { get; set; }
        public int ShoeID { get; set; }
        public int UserID { get; set; }
        public int Quantity { get; set; }
        public System.DateTime OrderDate { get; set; }
        public decimal Price { get; set; }
        public System.DateTime RowInsertTime { get; set; }
        public System.DateTime RowUpdateTime { get; set; }
    
        public virtual Shoess Shoess { get; set; }
        public virtual User User { get; set; }
    }
}
